name: Deploy App

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Ocean on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
       - name: Install Node Dependiencies
         with:
          node-version: '18.13.0'
          -run: npm install
          -run: npm run build


      - name: Deploy to Digital Ocean
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: /var/www/test/



